title: Awesome Bootcamp
author: Joe P
email: joepass456@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about Awesome Inc Bootcamp

# social links
twitter_username: ReallyJoePass # DO NOT include the @ character, or else the build will fail!
github_username:  JoePass456 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
